package org.mybatis.generator.mybatis3;

public class TawRoleDomainKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAW_ROLE_DOMAIN.DOMAIN_ID
     *
     * @mbggenerated Thu Dec 21 16:47:03 CST 2017
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAW_ROLE_DOMAIN.ROLE_ID
     *
     * @mbggenerated Thu Dec 21 16:47:03 CST 2017
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAW_ROLE_DOMAIN.DOMAIN_ID
     *
     * @return the value of TAW_ROLE_DOMAIN.DOMAIN_ID
     *
     * @mbggenerated Thu Dec 21 16:47:03 CST 2017
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAW_ROLE_DOMAIN.DOMAIN_ID
     *
     * @param domainId the value for TAW_ROLE_DOMAIN.DOMAIN_ID
     *
     * @mbggenerated Thu Dec 21 16:47:03 CST 2017
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAW_ROLE_DOMAIN.ROLE_ID
     *
     * @return the value of TAW_ROLE_DOMAIN.ROLE_ID
     *
     * @mbggenerated Thu Dec 21 16:47:03 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAW_ROLE_DOMAIN.ROLE_ID
     *
     * @param roleId the value for TAW_ROLE_DOMAIN.ROLE_ID
     *
     * @mbggenerated Thu Dec 21 16:47:03 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}