package org.mybatis.generator.mybatis3;

public class TawRoleDomain extends TawRoleDomainKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAW_ROLE_DOMAIN.DOMTYPEID
     *
     * @mbggenerated Thu Dec 21 16:47:03 CST 2017
     */
    private String domtypeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAW_ROLE_DOMAIN.DOMTYPEID
     *
     * @return the value of TAW_ROLE_DOMAIN.DOMTYPEID
     *
     * @mbggenerated Thu Dec 21 16:47:03 CST 2017
     */
    public String getDomtypeid() {
        return domtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAW_ROLE_DOMAIN.DOMTYPEID
     *
     * @param domtypeid the value for TAW_ROLE_DOMAIN.DOMTYPEID
     *
     * @mbggenerated Thu Dec 21 16:47:03 CST 2017
     */
    public void setDomtypeid(String domtypeid) {
        this.domtypeid = domtypeid;
    }
}