package org.mybatis.generator.mybatis3;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.generator.mybatis3.GausUserinfo;
import org.mybatis.generator.mybatis3.GausUserinfoExample;

public interface GausUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    int countByExample(GausUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    int deleteByExample(GausUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    int insert(GausUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    int insertSelective(GausUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    List<GausUserinfo> selectByExample(GausUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    GausUserinfo selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") GausUserinfo record, @Param("example") GausUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    int updateByExample(@Param("record") GausUserinfo record, @Param("example") GausUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    int updateByPrimaryKeySelective(GausUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GAUS_USERINFO
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    int updateByPrimaryKey(GausUserinfo record);
}