package org.mybatis.generator.mybatis3;

import java.util.Date;

public class GausUserinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.USERID
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.VERSIONID
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private Integer versionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.NAME
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.LOGINNAME
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.CREATEUSERNAME
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String createusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.PASSWORD
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.REGISTEDATE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private Date registedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.DESCRIPTION
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.EMAIL
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.GENDER
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.ADDRESS
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.PHONE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.MOBILE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.STATE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.ORGID
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.USERDEFINED1
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String userdefined1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.USERDEFINED2
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String userdefined2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.USERDEFINED3
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String userdefined3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GAUS_USERINFO.USERDEFINED4
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    private String userdefined4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.USERID
     *
     * @return the value of GAUS_USERINFO.USERID
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.USERID
     *
     * @param userid the value for GAUS_USERINFO.USERID
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.VERSIONID
     *
     * @return the value of GAUS_USERINFO.VERSIONID
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public Integer getVersionid() {
        return versionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.VERSIONID
     *
     * @param versionid the value for GAUS_USERINFO.VERSIONID
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setVersionid(Integer versionid) {
        this.versionid = versionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.NAME
     *
     * @return the value of GAUS_USERINFO.NAME
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.NAME
     *
     * @param name the value for GAUS_USERINFO.NAME
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.LOGINNAME
     *
     * @return the value of GAUS_USERINFO.LOGINNAME
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.LOGINNAME
     *
     * @param loginname the value for GAUS_USERINFO.LOGINNAME
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.CREATEUSERNAME
     *
     * @return the value of GAUS_USERINFO.CREATEUSERNAME
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getCreateusername() {
        return createusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.CREATEUSERNAME
     *
     * @param createusername the value for GAUS_USERINFO.CREATEUSERNAME
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setCreateusername(String createusername) {
        this.createusername = createusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.PASSWORD
     *
     * @return the value of GAUS_USERINFO.PASSWORD
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.PASSWORD
     *
     * @param password the value for GAUS_USERINFO.PASSWORD
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.REGISTEDATE
     *
     * @return the value of GAUS_USERINFO.REGISTEDATE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public Date getRegistedate() {
        return registedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.REGISTEDATE
     *
     * @param registedate the value for GAUS_USERINFO.REGISTEDATE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setRegistedate(Date registedate) {
        this.registedate = registedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.DESCRIPTION
     *
     * @return the value of GAUS_USERINFO.DESCRIPTION
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.DESCRIPTION
     *
     * @param description the value for GAUS_USERINFO.DESCRIPTION
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.EMAIL
     *
     * @return the value of GAUS_USERINFO.EMAIL
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.EMAIL
     *
     * @param email the value for GAUS_USERINFO.EMAIL
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.GENDER
     *
     * @return the value of GAUS_USERINFO.GENDER
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.GENDER
     *
     * @param gender the value for GAUS_USERINFO.GENDER
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.ADDRESS
     *
     * @return the value of GAUS_USERINFO.ADDRESS
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.ADDRESS
     *
     * @param address the value for GAUS_USERINFO.ADDRESS
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.PHONE
     *
     * @return the value of GAUS_USERINFO.PHONE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.PHONE
     *
     * @param phone the value for GAUS_USERINFO.PHONE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.MOBILE
     *
     * @return the value of GAUS_USERINFO.MOBILE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.MOBILE
     *
     * @param mobile the value for GAUS_USERINFO.MOBILE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.STATE
     *
     * @return the value of GAUS_USERINFO.STATE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.STATE
     *
     * @param state the value for GAUS_USERINFO.STATE
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.ORGID
     *
     * @return the value of GAUS_USERINFO.ORGID
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.ORGID
     *
     * @param orgid the value for GAUS_USERINFO.ORGID
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.USERDEFINED1
     *
     * @return the value of GAUS_USERINFO.USERDEFINED1
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getUserdefined1() {
        return userdefined1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.USERDEFINED1
     *
     * @param userdefined1 the value for GAUS_USERINFO.USERDEFINED1
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setUserdefined1(String userdefined1) {
        this.userdefined1 = userdefined1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.USERDEFINED2
     *
     * @return the value of GAUS_USERINFO.USERDEFINED2
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getUserdefined2() {
        return userdefined2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.USERDEFINED2
     *
     * @param userdefined2 the value for GAUS_USERINFO.USERDEFINED2
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setUserdefined2(String userdefined2) {
        this.userdefined2 = userdefined2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.USERDEFINED3
     *
     * @return the value of GAUS_USERINFO.USERDEFINED3
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getUserdefined3() {
        return userdefined3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.USERDEFINED3
     *
     * @param userdefined3 the value for GAUS_USERINFO.USERDEFINED3
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setUserdefined3(String userdefined3) {
        this.userdefined3 = userdefined3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GAUS_USERINFO.USERDEFINED4
     *
     * @return the value of GAUS_USERINFO.USERDEFINED4
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public String getUserdefined4() {
        return userdefined4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GAUS_USERINFO.USERDEFINED4
     *
     * @param userdefined4 the value for GAUS_USERINFO.USERDEFINED4
     *
     * @mbggenerated Mon Jan 29 17:45:04 CST 2018
     */
    public void setUserdefined4(String userdefined4) {
        this.userdefined4 = userdefined4;
    }
}